### ISSUE TITLE
Lacking Source Code

### ISSUE THREAD

**Issue by akfranco** [Bit-Nation/BRER#1]
A GitHub repository works best when it's populated with code relevant to the project.

**Comment by ccmawo** [comment]
At the moment there is not much code to share because the brer website uses wordpress and most of the page is saved in the wordpress database.

**Comment by akfranco** [comment]
Is the front-end otherwise neatly wrapped in a theme that can be shared?

**Comment by ETeissonniere** [comment]
There is now some code in the repo, closing.
